name: Autograding

on:
  push:
    branches:
      - main

jobs:
  autograde:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Java environment
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # Java version to use, adjust if needed

      # Compile the program
      - name: Compile the program
        run: javac -d bin $(find . -name "*.java")

      # Run the program and check the exit code
      - name: Run the program
        run: java -cp bin Main